### PR TITLE
Make ParameterDescription (and others) stack-safe

### LINKED ISSUE #148: StackOverflowError while preparing a statement
I tried to minimize the failing code:
```scala
object Main extends IOApp {

  val session: Resource[IO, Session[IO]] = ???

  def run(args: List[String]): IO[ExitCode] = session.use { s =>
    val list = List.fill(12000)("whatever")
    val values = text.values.list(list.length)

    val cmd = sql"VALUES $values".command

    s.prepare(cmd).use { ps => 
      IO.pure(ExitCode.Success)
    }
  }
```

Result:
```
ERROR java.lang.StackOverflowError
ERROR 	at scodec.bits.ByteVector.go$2(ByteVector.scala:230)
ERROR 	at scodec.bits.ByteVector.take(ByteVector.scala:237)
ERROR 	at scodec.bits.BitVector$.toBytes(BitVector.scala:1691)
ERROR 	at scodec.bits.BitVector$Bytes.take(BitVector.scala:1699)
ERROR 	at scodec.bits.BitVector$Bytes.take(BitVector.scala:1695)
ERROR 	at scodec.codecs.IntCodec.decode(IntCodec.scala:31)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
ERROR 	at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
ERROR 	at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
ERROR 	at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
... and so on
```

### PR DESCRIPTION
**Pull request by asoltysik**
Fixes #148

### CODE REVIEW

File: modules/core/src/main/scala/net/message/ParameterDescription.scala [hunk 1]
```diff
@@ -16,8 +14,6 @@ object ParameterDescription {
   final val Tag = 't'
 
   val decoder: Decoder[ParameterDescription] =
-    int16.flatMap { n =>
-      int32.asDecoder.replicateA(n).map(ParameterDescription(_))
-    }
+    codecs.listOfN(int16, int32).map(ParameterDescription(_))
```
Comment (asoltysik) [inline modules/core/src/main/scala/net/message/ParameterDescription.scala]: The StackOverflowError was being thrown by this line. So the same solution you provided in #148, just different place ;)

File: modules/core/src/main/scala/net/message/RowData.scala [hunk 2]
```diff
@@ -4,24 +4,23 @@
...
 
 object RowData {
 
-  private val field: Decoder[Option[String]] =
+  private val field: Codec[Option[String]] =
     int32.flatMap {
       case -1 => Decoder.point(None)
       case n  => bytes(n).map(bv => Some(new String(bv.toArray, UTF_8)))
-    }
+    }.decodeOnly
```
Comment (asoltysik) [inline modules/core/src/main/scala/net/message/RowData.scala]: `listOfN` requires `Codec`

File: modules/core/src/main/scala/net/message/RowData.scala [hunk 3]
```diff
@@ -4,24 +4,23 @@
...
 
   final val Tag = 'D'
-  final val decoder: Decoder[RowData] = int16.flatMap(field.replicateA(_)).map(apply)
+  final val decoder: Decoder[RowData] = 
+    codecs.listOfN(int16, field).map(apply)
```
Comment (asoltysik) [inline modules/core/src/main/scala/net/message/RowData.scala]: Also changed other occurrences of `replicateA` cause they also might potentially blow up?

File: modules/tests/src/test/scala/ListTest.scala [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+import skunk._
+import skunk.codec.all._
+import skunk.implicits._
+
+case object ListTest extends SkunkTest {
+ 
+ // Regression test for https://github.com/tpolecat/skunk/issues/148
+  sessionTest("Do not throw StackOverflowError on big list encoders") { s =>
+    val aLotOfStrings = List.fill(Short.MaxValue)("foo")
```
Comment (asoltysik) [inline modules/tests/src/test/scala/ListTest.scala]: @tpolecat Unrelated: An error is thrown when the list length is bigger than 16 bit integer, e.g. replacing `Short.MaxValue` with `Short.MaxValue + 1` leads to this:
`java.lang.IllegalArgumentException: 32768 is greater than maximum value 32767 for 16-bit signed integer`.

Is there a particular reason for disallowing bigger lists?

**Comment by asoltysik** [comment]
The CI was green before I rebased so it **might** not be my fault :)
